name: 'build Windows'
description: 'build Windows package'
inputs:
  love-url:
    required: true
  love-dir:
    required: true
  arch:
    required: true
  version:
    required: true
  icon:
    required: true
runs:
  using: "composite"
  steps:
    - name: Download love
      uses: ./.github/actions/get-unzip
      with:
        url: ${{ inputs.love-url }}
    - name: move love
      shell: bash
      run: mv ${{ inputs.love-dir }} love
    - name: Download ColdClear
      uses: ./.github/actions/get-cc
      with:
        arch: ${{ inputs.arch }}
    - name: Download ResourceHacker
      uses: ./.github/actions/get-unzip
      with:
        url: http://www.angusj.com/resourcehacker/resource_hacker.zip
    - uses: ./.github/actions/build-love
    - name: update Windows template
      shell: bash
      run: |
        perl -p -e '
          my $version = "${{ inputs.version }}";
          $version =~ s/V//g;
          my $fileVersion = $version.",0";
          $fileVersion =~ s/\./,/g;
          s/\@FileVersion/$fileVersion/g;
          s/\@Version/$version/g;
        ' .github/build/Windows/Techmino.rc.template > Techmino.rc
    - name: Pack Techmino
      shell: pwsh
      run: |
        cmd /c copy /b .\love\love.exe + .\Techmino.love .\love\Techmino.exe
        del .\love\love.exe
        del .\love\lovec.exe
        del .\love\game.ico
        del .\love\love.ico
        del .\love\changes.txt
        del .\love\readme.txt
        move .\cold_clear.dll .\love
        move .\CCloader.dll .\love
        cmd /c '.\ResourceHacker.exe -open .\love\Techmino.exe -save .\love\Techmino.exe -action delete -mask ICONGROUP,,'
        cmd /c '.\ResourceHacker.exe -open .\Techmino.rc -save .\Techmino.res -action compile'
        cmd /c '.\ResourceHacker.exe -open .\love\Techmino.exe -save .\love\Techmino.exe -action addoverwrite -res "${{ inputs.icon }}" -mask ICONGROUP,1,'
        cmd /c '.\ResourceHacker.exe -open .\love\Techmino.exe -save .\love\Techmino.exe -action addoverwrite -res ".\Techmino.res" -mask VERSIONINFO,1,'
