name: 'update version'
description: 'common update logic for snapshot and release'
inputs:
  commit:
    required: false
  type:
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      name: update snapshot saving folder
      run: |
        perl -p -e "
          s/t.identity='Techmino'/t.identity='Techmino_Snapshot'/g
            if lc('${{ inputs.type }}') eq 'snapshot'
        " -i conf.lua
    - shell: bash
      run: |
        perl -p -e '
          $v = "${{ inputs.commit }}";
          $v = "@".substr($v, 0, 4) if $v;
          s/\@DEV/$v/g
        ' -i version.lua
